/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.Confige;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.dbAccessor;

/**
 *
 * @author m.j
 */
public class formCustomer extends javax.swing.JFrame {
private LoginFormS loginforms;
private dbAccessor accessor;
    private ResourceBundle rs=Confige.getConfic().getResourceBundle();

    /**
     * Creates new form formCustomer
     */
    public formCustomer() {
    try {
          initComponents();
          JPanel p=(JPanel) getContentPane();
             
                  switch(rs.getLocale().getLanguage()){
            case "en":
                 p.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
                    
                break;
                case"fa":
                    p.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
                    break;
        }
        rs=Confige.getConfic().getResourceBundle();

       accessor=   dbAccessor.GetAccessor();
    loginforms=LoginFormS.GetLogin();
      loginforms.setEnabled(false);
      firstErrM.setVisible(false);
            lastErrM1.setVisible(false);
            addressEM.setVisible(false);
            tellErrM.setVisible(false);
            this.setResizable(false);
    } catch (Exception ex) {
        Logger.getLogger(formCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
      
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension frameSize = getSize();
            setLocation(new Point((screenSize.width - frameSize.width) / 2,
                    (screenSize.height - frameSize.width) / 2));
            
       
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        last = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tell = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sexM = new javax.swing.JRadioButton();
        sexF = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        firstErrM = new javax.swing.JLabel();
        lastErrM1 = new javax.swing.JLabel();
        tellErrM = new javax.swing.JLabel();
        addressEM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText(rs.getString("FirstName"));

        last.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastFocusLost(evt);
            }
        });
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });

        jLabel2.setText(rs.getString("LastName")
        );

        first.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstFocusLost(evt);
            }
        });
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });

        jLabel3.setText(rs.getString("Address"));

        add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addFocusLost(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel4.setText(rs.getString("Tell"));

        tell.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tellFocusLost(evt);
            }
        });
        tell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tellActionPerformed(evt);
            }
        });

        jLabel5.setText(rs.getString("Sex"));

        buttonGroup2.add(sexM);
        sexM.setSelected(true);
        sexM.setText(rs.getString("Male"));
        sexM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexMActionPerformed(evt);
            }
        });

        buttonGroup2.add(sexF);
        sexF.setText(rs.getString("FeMale"));
        sexF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexFActionPerformed(evt);
            }
        });

        jButton1.setText(rs.getString("Add"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        firstErrM.setForeground(new java.awt.Color(255, 0, 51));
        firstErrM.setIcon(new javax.swing.ImageIcon("C:\\Users\\m.j\\Documents\\NetBeansProjects\\store\\nok.png")); // NOI18N
        firstErrM.setText(rs.getString("Err"));

        lastErrM1.setForeground(new java.awt.Color(255, 0, 51));
        lastErrM1.setIcon(new javax.swing.ImageIcon("C:\\Users\\m.j\\Documents\\NetBeansProjects\\store\\nok.png")); // NOI18N
        lastErrM1.setText(rs.getString("Err"));

        tellErrM.setForeground(new java.awt.Color(255, 0, 51));
        tellErrM.setIcon(new javax.swing.ImageIcon("C:\\Users\\m.j\\Documents\\NetBeansProjects\\store\\nok.png")); // NOI18N
        tellErrM.setText(rs.getString("Err"));

        addressEM.setForeground(new java.awt.Color(255, 0, 51));
        addressEM.setIcon(new javax.swing.ImageIcon("C:\\Users\\m.j\\Documents\\NetBeansProjects\\store\\nok.png")); // NOI18N
        addressEM.setText(rs.getString("Err"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sexM)
                        .addGap(36, 36, 36)
                        .addComponent(sexF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastErrM1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstErrM, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressEM, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tell, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tellErrM, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastErrM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sexM)
                    .addComponent(sexF))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstErrM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressEM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tellErrM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
      loginforms.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
      
        
    }//GEN-LAST:event_lastActionPerformed

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_firstActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_addActionPerformed

    private void tellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tellActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tellActionPerformed

    private void sexMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexMActionPerformed
        // TODO add your handling code here:
        first.setEnabled(true);
        
    }//GEN-LAST:event_sexMActionPerformed

    private void sexFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexFActionPerformed
        // TODO add your handling code here:
        first.setEnabled(false);
    }//GEN-LAST:event_sexFActionPerformed

    private void lastFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastFocusLost
        // TODO add your handling code here:
        String namelast=last.getText();
        String pattern="[a-z]{4,10}";
        if(!namelast.matches(pattern))
            lastErrM1.setVisible(true);
        else
            lastErrM1.setVisible(false);
         
    }//GEN-LAST:event_lastFocusLost

    private void firstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstFocusLost
        // TODO add your handling code here:
          String namelast=first.getText();
        String pattern="[a-z]{4,10}";
        if(!namelast.matches(pattern))
            firstErrM.setVisible(true);
        else
           firstErrM.setVisible(false);
        
    }//GEN-LAST:event_firstFocusLost

    private void addFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addFocusLost
        // TODO add your handling code here:
        String namelast=add.getText();
        String pattern="[a-z]{0,15}[0-9]{0,5}";
        if(!namelast.matches(pattern))
            addressEM.setVisible(true);
        else
            addressEM.setVisible(false);
    }//GEN-LAST:event_addFocusLost

    private void tellFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tellFocusLost
        // TODO add your handling code here:
          String namelast=tell.getText();
        String pattern="\\d{0,13}";
        if(!namelast.matches(pattern))
               tellErrM.setVisible(true);
        else
            tellErrM.setVisible(false);
        
    }//GEN-LAST:event_tellFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s=null;
        if(sexM.isSelected())
            s=sexM.getText();
        if(sexF.isSelected())
            s=sexF.getText();
        String first1=null;
        if(first.getText()!="")
        first1=first.getText();
       
        
  boolean b=accessor.addCustomer(first1, s, last.getText(),add.getText() , tell.getText() );
if(b==true){
    JOptionPane.showMessageDialog(this,"YourCustomerAdded");
    first.setText("");
    last.setText("");
    add.setText("");
    tell.setText("");
    sexF.setSelected(false);
    sexM.setSelected(false);
    first.setEnabled(true);
}
    }//GEN-LAST:event_jButton1ActionPerformed

//private void group(){
//     ButtonGroup group1=new ButtonGroup();
//     group1.add(sexF);
//     group1.add(sexM);
//}


    /**
//     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(formCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new formCustomer(this).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JLabel addressEM;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField first;
    private javax.swing.JLabel firstErrM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField last;
    private javax.swing.JLabel lastErrM1;
    private javax.swing.JRadioButton sexF;
    private javax.swing.JRadioButton sexM;
    private javax.swing.JTextField tell;
    private javax.swing.JLabel tellErrM;
    // End of variables declaration//GEN-END:variables
}
